from db_config import get_connection

conn = get_connection()
cursor = conn.cursor()

# create USERS table 
cursor.execute("""
CREATE TABLE users (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(50) NOT NULL,
    prenom VARCHAR2(50) NOT NULL,
    cin VARCHAR2(50) UNIQUE NOT NULL,
    email VARCHAR2(100) NOT NULL,
    created_at DATE DEFAULT SYSDATE
)
""")

# create CATEGORIES table 
cursor.execute("""
CREATE TABLE categories (
    category_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name VARCHAR2(50) UNIQUE NOT NULL,
    description VARCHAR2(150)
)
""")

# Create EXPENSES table 
cursor.execute("""
CREATE TABLE expenses (
    expense_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER REFERENCES users(user_id),
    category_id NUMBER REFERENCES categories(category_id),
    amount NUMBER(10,2),
    expense_date DATE DEFAULT SYSDATE,
    description VARCHAR2(100)
)
""")

# Create INCOME table
cursor.execute("""
CREATE TABLE income (
    income_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER REFERENCES users(user_id),
    source VARCHAR2(100),
    amount NUMBER(10,2) NOT NULL,
    income_date DATE DEFAULT SYSDATE,
    notes VARCHAR2(100)
)
""")

#  Create BUDGETS table 
cursor.execute("""
CREATE TABLE budgets (
    budget_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER REFERENCES users(user_id),
    category_id NUMBER REFERENCES categories(category_id),
    amount_limit NUMBER(10,2),
    month_year VARCHAR2(7)
)
""")

conn.commit()
cursor.close()
conn.close()

print("✅ All tables created successfully!")
